[package]
name = "lsai"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"]}
serde = { version = "1", features = ["derive"]}
serde_json = "1"

reqwest = {version = "0.12", features = ["json", "rustls-tls"]}
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
anyhow = "1"
